export enum S3StorageClass {
  DEFAULT = '',
  STANDARD = 'STANDARD',
  STANDARD_IA = 'STANDARD_IA',
  ONEZONE_IA = 'ONEZONE_IA',
  INTELLIGENT_TIERING = 'INTELLIGENT_TIERING',
  REDUCED_REDUNDANCY = 'REDUCED_REDUNDANCY',
  GLACIER_IR = 'GLACIER_IR',
}
