FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      ca-certificates curl docker.io jq && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
ENTRYPOINT []
